---
abstract: 'A list of all Perl 5 built functions'
author:
  - 'David Farrell <sillymoos@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Builtins
requires:
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/sillymoose/Perl-Builtins
  repository: https://github.com/sillymoose/Perl-Builtins.git
version: '0.01'
